# Generated by Django 4.2.3 on 2023-07-28 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Строительные материалы ', 'Строительные материалы'), ('Аренда спецтехники', 'Аренда спецтехники'), ('Благоустройство территории', 'Благоустройство территории'), ('Асфальтирование', 'Асфальтирование'), ('Ремонт дорог', 'Ремонт дорог'), ('Грунт', 'Грунт'), ('Дорожные работы', 'Дорожные работы'), ('Земляные работы и прочие работы', 'Земляные работы и прочие работы'), ('Тротуарная бетонная плитка и бордюры', 'Тротуарная бетонная плитка и бордюры'), ('Другое', 'Другое')], default='Другое', max_length=100, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img/')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('image', models.ImageField(upload_to='img/', verbose_name='Текущее фото')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
